hide and seek game
clovercraft/denizen pull request #19
Opened 2023-04-04 05:05 UTC by danielbernard

see commit comments related to `end` command; I may have misunderstood the request.
still needs on-tag and game clock world scripts.

2023-04-05 03:26 UTC, mmsheeks commented
As for what you wrote for the end commands, that looks clean and follows the logic I intended, I must have just finished documenting the feature fully. This is great bud, thanks. I'll leave the PR here and whichever of us gets to the world scripts first can wrap it up.

2023-04-07 19:21 UTC, danielbernard commented
@mmsheeks I wasn't able to test the on-tag stuff solo; if you want to work together to test this sometime

2023-04-14 01:21 UTC, mmsheeks requested changes

2023-04-14 01:21 UTC, mmsheeks commented on modules/hide-and-seek/commands/join.dsc
> +            - flag player hs_active expire:12h
Can you apply a flag without providing a value? Entirely possible this works, just not certain.

2023-04-14 01:21 UTC, mmsheeks commented on modules/hide-and-seek/on-tag.dsc
> +                - narrate "<aqua><[tagged]> was found by <player>!<reset>" targets:<[remaining_players]>
this will need to be `<[tagged].display_name>` or similar to show a valid name, rather than a (text converted) player tag (i.e. `p@uuids-are-very-long-in-this-game`).

If you can make this update, I'll get the changes merged in and we can test on the server.

2023-04-14 01:23 UTC, danielbernard commented on modules/hide-and-seek/commands/join.dsc
> +            - flag player hs_active expire:12h
yeah, seemed to work anyways

2023-04-14 01:25 UTC, danielbernard commented on modules/hide-and-seek/on-tag.dsc
> +                - narrate "<aqua><[tagged]> was found by <player>!<reset>" targets:<[remaining_players]>
done 👍

2023-04-14 01:26 UTC, mmsheeks approved these changes

2023-04-14 01:26 UTC, merged